### ISSUE TITLE
Outbound endpoint create exchange + binding + queue

### ISSUE THREAD

**Issue by dietervanhoof** [mulesoft/mule-transport-amqp#101]
I have found #69 and copy-pasted the [referenced documentation](https://github.com/mulesoft/mule-transport-amqp/blob/master/GUIDE.md#listen-to-messages-with-exchange-re-declaration-and-queue-creation) yet Mule provides me with the following error (I have set exchange-pattern to request-response to see what is going on):

```
*******************************************************************************************************
*            - - + APPLICATION + - -            *       - - + DOMAIN + - -       * - - + STATUS + - - *
*******************************************************************************************************
* queuetest                                     * default                        * DEPLOYED           *
*******************************************************************************************************

INFO  2016-02-01 14:50:57,707 [[queuetest].queuetestFlow.stage1.02] com.mulesoft.weave.mule.utils.MuleWeaveFactory$: MimeType was not resolved '*/*' delegating to Java.
INFO  2016-02-01 14:50:58,218 [[queuetest].queuetestFlow.stage1.02] org.mule.transport.service.DefaultTransportServiceDescriptor: Loading default outbound transformer: org.mule.transport.amqp.internal.transformer.ObjectToAmqpMessage
INFO  2016-02-01 14:50:58,219 [[queuetest].queuetestFlow.stage1.02] org.mule.transport.service.DefaultTransportServiceDescriptor: Loading default response transformer: org.mule.transport.amqp.internal.transformer.ObjectToAmqpMessage
INFO  2016-02-01 14:50:58,223 [[queuetest].queuetestFlow.stage1.02] org.mule.lifecycle.AbstractLifecycleManager: Initialising: 'AMQP_0_9_Connector.dispatcher.1733469121'. Object is: Dispatcher
WARN  2016-02-01 14:50:58,224 [[queuetest].queuetestFlow.stage1.02] org.mule.transport.service.DefaultTransportServiceDescriptor: Couldn't not find org.mule.transport.amqp.internal.domain.AmqpMuleMessageFactory empty constructor. org.mule.transport.amqp.internal.domain.AmqpMuleMessageFactory must be updated to have an empty constructor in order to work properly within domains.
INFO  2016-02-01 14:50:58,263 [[queuetest].queuetestFlow.stage1.02] org.mule.lifecycle.AbstractLifecycleManager: Starting: 'AMQP_0_9_Connector.dispatcher.1733469121'. Object is: Dispatcher
ERROR 2016-02-01 14:50:58,428 [[queuetest].queuetestFlow.stage1.02] org.mule.exception.DefaultMessagingExceptionStrategy: 
********************************************************************************
Message               : Failed to route event via endpoint: DefaultOutboundEndpoint{endpointUri=amqp://my-exchange, connector=AmqpConnector
{
  name=AMQP_0_9_Connector
  lifecycle=start
  this=24e83d19
  numberOfConcurrentTransactedReceivers=4
  createMultipleTransactedReceivers=true
  connected=true
  supportedProtocols=[amqp]
  serviceOverrides=<none>
}
,  name='endpoint.amqp.my.exchange', mep=REQUEST_RESPONSE, properties={exchangeType=fanout, routingKey=my-key}, transactionConfig=Transaction{factory=null, action=INDIFFERENT, timeout=0}, deleteUnacceptedMessages=false, initialState=started, responseTimeout=10000, endpointEncoding=UTF-8, disableTransportTransformer=false}. Message payload is of type: AmqpMessage
Type                  : org.mule.api.transport.DispatchException
Code                  : MULE_ERROR--2
JavaDoc               : http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/transport/DispatchException.html
Payload               : org.mule.transport.amqp.internal.domain.AmqpMessage@4d344848[consumerTag=<null>,envelope=Envelope(deliveryTag=0, redeliver=false, exchange=null, routingKey=null),body={60,63,120,109,108,32,118,101,114,115,105,111,110,61,39,49,46,48,39,32,101,110,99,111,100,105,110,103,61,39,85,84,70,45,56,39,63,62,10,60,114,111,111,116,62,10,32,32,60,102,105,101,108,100,111,110,101,62,102,105,101,108,100,111,110,101,118,97,108,117,101,60,47,102,105,101,108,100,111,110,101,62,10,32,32,60,102,105,101,108,100,116,119,111,62,102,105,101,108,100,116,119,111,118,97,108,117,101,60,47,102,105,101,108,100,116,119,111,62,10,60,47,114,111,111,116,62},properties=#contentHeader<basic>(content-type=null, content-encoding=UTF-8, headers={MULE_SESSION=rO0ABXNyACNvcmcubXVsZS5zZXNzaW9uLkRlZmF1bHRNdWxlU2Vzc2lvbi7rdtEW7GGKAwAFWgAFdmFsaWRMAA1mbG93Q29uc3RydWN0dAAmTG9yZy9tdWxlL2FwaS9jb25zdHJ1Y3QvRmxvd0NvbnN0cnVjdDtMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wACnByb3BlcnRpZXN0AA9MamF2YS91dGlsL01hcDtMAA9zZWN1cml0eUNvbnRleHR0ACdMb3Jn...
********************************************************************************
Exception stack is:
1. channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'my-exchange' in vhost '/', class-id=60, method-id=40) (com.rabbitmq.client.ShutdownSignalException)
  com.rabbitmq.client.impl.ChannelN:478 (null)
2. channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'my-exchange' in vhost '/', class-id=60, method-id=40) (com.rabbitmq.client.ShutdownSignalException)
  com.rabbitmq.utility.ValueOrException:67 (null)
3. null (java.io.IOException)
  com.rabbitmq.client.impl.AMQChannel:106 (null)
4. Failed to route event via endpoint: DefaultOutboundEndpoint{endpointUri=amqp://my-exchange, connector=AmqpConnector
{
  name=AMQP_0_9_Connector
  lifecycle=start
  this=24e83d19
  numberOfConcurrentTransactedReceivers=4
  createMultipleTransactedReceivers=true
  connected=true
  supportedProtocols=[amqp]
  serviceOverrides=<none>
}
,  name='endpoint.amqp.my.exchange', mep=REQUEST_RESPONSE, properties={exchangeType=fanout, routingKey=my-key}, transactionConfig=Transaction{factory=null, action=INDIFFERENT, timeout=0}, deleteUnacceptedMessages=false, initialState=started, responseTimeout=10000, endpointEncoding=UTF-8, disableTransportTransformer=false}. Message payload is of type: AmqpMessage (org.mule.api.transport.DispatchException)
  org.mule.transport.AbstractMessageDispatcher:117 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/transport/DispatchException.html)
********************************************************************************
Root Exception stack trace:
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'my-exchange' in vhost '/', class-id=60, method-id=40)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:478)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:315)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:550)
	at java.lang.Thread.run(Thread.java:745)

********************************************************************************
```

Looking at this:
`reply-code=404, reply-text=NOT_FOUND - no exchange 'my-exchange' in vhost '/'`

My intention is to make Mule create an exchange, create a queue and add a binding to the exchange to that queue.

I have attached a sample project. Fill in the host, username and password in the properties file (rabbit.host, rabbit.username, rabbit.password) and run.
[queuetest.zip](https://github.com/mulesoft/mule-transport-amqp/files/112321/queuetest.zip)

**Comment by dietervanhoof** [comment]
I have tried exactly the same with an inbound endpoint and it works as expected. Creates an exchange, a queue and the binding.

**Comment by dietervanhoof** [comment]
It seems f0ee09353eef1ecb1d4165f21444bbae485c31cc fixes the issue of declaring queues. I will test out exchanges.
